### ISSUE TITLE
feat: User authentication

### ISSUE THREAD

**Issue by SINJINI-G** [Fenrir-04/Algo-Media#6] opened 2023-05-20 11:37 UTC
I will make a signup component for users to create new user account.

Can you please assign this issue to me for gssoc 2023? @Fenrir-04

**Comment by ayesha-firdaus** [comment] 2023-05-20 16:03
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by Fenrir-04** [comment] 2023-05-21 05:10
Thanks for your feedback.
But this issue is already assigned to someone else.

**Closed by Fenrir-04** 2023-05-21 05:10 UTC
